//Checkout Action
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_DELIVERY_SUCCESS = "CHECKOUT_DELIVERY_SUCCESS";
export const CHECKOUT_PAYMENT_SUCCESS = "CHECKOUT_PAYMENT_SUCCESS";
export const CHECKOUT_FINISH_SUCCESS = "CHECKOUT_FINISH_SUCCESS";
export const CHECKOUT_BACK_DELIVERY = "CHECKOUT_BACK_DELIVERY";
export const CHECKOUT_SHIPPING_FEE = "CHECKOUT_SHIPPING_FEE";
export const CHECKOUT_DROPSHIPPING_FEE = "CHECKOUT_DROPSHIPPING_FEE";
